# Step 1: Extract (Web Scraping)

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
URL = "https://www.gulftalent.com/jobs/search?pos_ref=Data&frmPositionCountry=#!?category=&industry=&seniority=&country=&city=&employment_type=&has_external_application=&keyword=Data"

In [3]:
r = requests.get(URL)
soup = BeautifulSoup(r.text)
job_list_html = soup.find_all(class_='ga-job-impression ga-job-click job-results-item section')

In [8]:
job_list_html = soup.find_all(class_='ga-job-impression ga-job-click job-results-item section')

In [9]:

list_of_dict = []
for job in job_list_html:
    position = job.find(class_='title').text.strip()
    date = job.find(class_='date').text.strip()
    company = job.find(class_="company-name").text.strip()
    location = job.find(class_="location").text.strip()
    detail_link = job['href']
    
    dict_ = { 
        "position" : position,
        "date" : date,
        "company" : company,
        "location" :location,
        "detail_link" : detail_link
        }
    list_of_dict.append(dict_)

In [10]:
df = pd.DataFrame(list_of_dict)
df

,position,date,company,location,detail_link
0,Data Analyst / Specialist,9 Aug 2023,Ultimate HR Solutions,Dubai,/mobile/uae/jobs/data-analyst-specialist-382848
1,Data Strategy Consultant,22 Sep 2023,Core Consultants,UAE,/mobile/uae/jobs/data-strategy-consultant-388588
2,Data Manager - Consulting Technology,29 Oct 2023,PricewaterhouseCoopers,Riyadh,/mobile/saudi-arabia/jobs/data-manager-consult...
3,Data Science Manager,25 Oct 2023,Deloitte & Touche (M.E.),Riyadh,/mobile/saudi-arabia/jobs/data-science-manager...
4,Data Entry Officer - 6 Months (Extendable),18 Jul 2023,ManpowerGroup Middle East,Dubai,/mobile/uae/jobs/data-entry-officer-6-months-e...
5,Data Analytics Lead,26 Jul 2023,Michael Page,UAE,/mobile/uae/jobs/data-analytics-lead-381356
6,Data Governance Director (Metadata),1 Aug 2023,Michael Page,UAE,/mobile/uae/jobs/data-governance-director-meta...
7,Data Governance Manager,3 Aug 2023,Michael Page,UAE,/mobile/uae/jobs/data-governance-manager-382246
8,Data Engineering Manager,3 Aug 2023,Michael Page,UAE,/mobile/uae/jobs/data-engineering-manager-382247
9,Data Scientist Manager,9 Aug 2023,Michael Page,Saudi Arabia,/mobile/saudi-arabia/jobs/data-scientist-manag...
10,Data Analyst,31 Jul 2023,Flow Talent,Abu Dhabi,/mobile/uae/jobs/data-analyst-384706
11,Data Architect,1 Sep 2023,Michael Page,UAE,/mobile/uae/jobs/data-architect-385954
12,Data Engineer,18 Sep 2023,ManpowerGroup Middle East,Saudi Arabia,/mobile/saudi-arabia/jobs/data-engineer-388119
13,Data Entry/Admin,19 Sep 2023,ManpowerGroup Middle East,UAE,/mobile/uae/jobs/data-entry-admin-389772
14,Data and Information Management Team Lead,3 Nov 2023,Charterhouse,Dubai,/mobile/uae/jobs/data-and-information-manageme...
15,Data Center Manager,19 Jun 2023,Innovative Contractors for Advanced Dimensions...,Saudi Arabia,/mobile/saudi-arabia/jobs/data-center-manager-...
16,Data Analyst,21 Aug 2023,RTC-1 Employment Services,Dubai,/mobile/uae/jobs/data-analyst-384081
17,Data Engineer - Data Integration,9 Nov 2023,IBM Middle East,Cairo,/mobile/egypt/jobs/data-engineer-data-integrat...
18,Data Analyst,26 Oct 2023,Quest Search & Selection,Qatar,/mobile/qatar/jobs/data-analyst-392756
19,Data Scientist - Senior Specialist,31 Oct 2023,Michael Page,UAE,/mobile/uae/jobs/data-scientist-senior-special...
20,Data Analytics Manager,7 Nov 2023,Ooredoo,Muscat,/mobile/oman/jobs/data-analytics-manager-393920
21,Data Scientist,4 Jul 2023,Michael Page,UAE,/mobile/uae/jobs/data-scientist-378508
22,Data Analytics Internal Audit Manager,8 Sep 2023,Flow Talent,Dubai,/mobile/uae/jobs/data-analytics-internal-audit...
23,Data Consultant,4 Jul 2023,Michael Page,UAE,/mobile/uae/jobs/data-consultant-378510
24,Data Analyst / Audit Analyst,1 Sep 2023,Deloitte & Touche (M.E.),Khobar,/mobile/saudi-arabia/jobs/data-analyst-audit-a...

# Step 2: Transform (Data Transformation)

In [100]:
base_url = "https://www.gulftalent.com"
df['detail_link'] = df['detail_link'].apply(lambda x: base_url + x.replace("/mobile", ""))

In [101]:
df['date'] = pd.to_datetime(df['date'])

In [102]:
df

,position,date,company,location,detail_link
0,Data Strategy Consultant,2023-09-22,Core Consultants,UAE,https://www.gulftalent.com/uae/jobs/data-strat...
1,Data Analyst / Specialist,2023-08-09,Ultimate HR Solutions,Dubai,https://www.gulftalent.com/uae/jobs/data-analy...
2,Data Manager - Consulting Technology,2023-10-29,PricewaterhouseCoopers,Riyadh,https://www.gulftalent.com/saudi-arabia/jobs/d...
3,Data Entry Officer - 6 Months (Extendable),2023-07-18,ManpowerGroup Middle East,Dubai,https://www.gulftalent.com/uae/jobs/data-entry...
4,Data Analytics Lead,2023-07-26,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-analy...
5,Data Governance Manager,2023-08-03,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-gover...
6,Data Engineering Manager,2023-08-03,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-engin...
7,Data Architect,2023-09-01,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-archi...
8,Data Science Manager,2023-10-25,Deloitte & Touche (M.E.),Riyadh,https://www.gulftalent.com/saudi-arabia/jobs/d...
9,Data Engineer,2023-09-18,ManpowerGroup Middle East,Saudi Arabia,https://www.gulftalent.com/saudi-arabia/jobs/d...
10,Data Center Manager,2023-06-19,Innovative Contractors for Advanced Dimensions...,Saudi Arabia,https://www.gulftalent.com/saudi-arabia/jobs/d...
11,Data Governance Director (Metadata),2023-08-01,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-gover...
12,Data Scientist Manager,2023-08-09,Michael Page,Saudi Arabia,https://www.gulftalent.com/saudi-arabia/jobs/d...
13,Data Analyst,2023-08-21,RTC-1 Employment Services,Dubai,https://www.gulftalent.com/uae/jobs/data-analy...
14,Data Analyst,2023-07-31,Flow Talent,Abu Dhabi,https://www.gulftalent.com/uae/jobs/data-analy...
15,Data Entry/Admin,2023-09-19,ManpowerGroup Middle East,UAE,https://www.gulftalent.com/uae/jobs/data-entry...
16,Data Engineer - Data Integration,2023-11-03,IBM Middle East,Cairo,https://www.gulftalent.com/egypt/jobs/data-eng...
17,Data Analyst,2023-10-26,Quest Search & Selection,Qatar,https://www.gulftalent.com/qatar/jobs/data-ana...
18,Data Scientist - Senior Specialist,2023-10-31,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-scien...
19,Data and Information Management Team Lead,2023-11-03,Charterhouse,Dubai,https://www.gulftalent.com/uae/jobs/data-and-i...
20,Data Scientist,2023-07-04,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-scien...
21,Data Analytics Internal Audit Manager,2023-09-08,Flow Talent,Dubai,https://www.gulftalent.com/uae/jobs/data-analy...
22,Data Consultant,2023-07-04,Michael Page,UAE,https://www.gulftalent.com/uae/jobs/data-consu...
23,Data Analyst / Audit Analyst,2023-09-01,Deloitte & Touche (M.E.),Khobar,https://www.gulftalent.com/saudi-arabia/jobs/d...
24,Head of Data Privacy Advisory and Governance,2023-09-27,Michael Page,Saudi Arabia,https://www.gulftalent.com/saudi-arabia/jobs/h...

In [118]:
df.dtypes

position               object
date           datetime64[ns]
company                object
location               object
detail_link            object
dtype: object

# Step 3: Load

In [120]:
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, Session
from sqlalchemy import Column, Date, String

### Create Database

In [132]:
db_info = {
    "username":"postgres",
    "password": "sina2000",
    "host": "localhost",
    "port": 5432,
    "database": "postgres"
}

In [143]:
def create_database(db_name):
        
    # Database Info
    username = db_info["username"]
    password = db_info["password"]
    host = db_info["host"]
    port = db_info["port"]
    database = db_info["database"]
    
    # Create Engine for Connection
    engine = create_engine(f"postgresql://{username}:{password}@{host}:{port}/{database}")
    
    # Connection
    conn = engine.connect()
    
    # Create Database
    conn.execute("COMMIT")
    conn.execute(f"CREATE DATABASE {db_name}")
    conn.close()

In [145]:
#create_database("test_sn")

### Create Table with SQLalchemy (ORM)

In [139]:
def db_connection(db_name):
    # Database Info
    username = db_info["username"]
    password = db_info["password"]
    host = db_info["host"]
    port = db_info["port"]
    database = db_info["database"]
    
    # Create Engine for Connection
    engine = create_engine(f"postgresql://{username}:{password}@{host}:{port}/{db_name}")
    session = Session(engine)
    Base = declarative_base()

    return engine, session, Base

In [140]:
engine, session, Base = db_connection("test_sn")

In [141]:
class JobList(Base):
    extend_existing=True
    __tablename__ = "joblist_db"
    id = Column(Integer, primary_key=True)
    position = Column(String)    
    date = Column(Date)
    company = Column(String)
    location = Column(String)
    detail_link = Column(String)

In [142]:
Base.metadata.create_all(engine)

### Insert Data

In [155]:
list_of_job_row = [JobList(**job_item_dict) for job_item_dict in df.to_dict(orient="records")]

In [156]:
list_of_job_row

[<__main__.JobList at 0x232d695c4d0>,
 <__main__.JobList at 0x232d678af10>,
 <__main__.JobList at 0x232d695dcd0>,
 <__main__.JobList at 0x232d6810690>,
 <__main__.JobList at 0x232d6962350>,
 <__main__.JobList at 0x232d69624d0>,
 <__main__.JobList at 0x232d6962610>,
 <__main__.JobList at 0x232d6962090>,
 <__main__.JobList at 0x232d6962690>,
 <__main__.JobList at 0x232d6962550>,
 <__main__.JobList at 0x232d6962450>,
 <__main__.JobList at 0x232d6949050>,
 <__main__.JobList at 0x232d6949810>,
 <__main__.JobList at 0x232d6948f50>,
 <__main__.JobList at 0x232d6948ad0>,
 <__main__.JobList at 0x232d694bd90>,
 <__main__.JobList at 0x232d69490d0>,
 <__main__.JobList at 0x232d694bd50>,
 <__main__.JobList at 0x232d6949a90>,
 <__main__.JobList at 0x232d694bb90>,
 <__main__.JobList at 0x232d69500d0>,
 <__main__.JobList at 0x232d6953710>,
 <__main__.JobList at 0x232d6950650>,
 <__main__.JobList at 0x232d69524d0>,
 <__main__.JobList at 0x232d6950cd0>]

In [157]:
session.add_all(list_of_job_row)

In [158]:
session.commit()